spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lmall
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

server:
  port: 8081

grpc:
  server:
    port: 9090
  client:
    inventory-service:
      address: static://localhost:9091
      negotiationType: PLAINTEXT

rabbitmq:
  exchanges:
    order: order.exchange
  queues:
    order-creation: order.creation.queue
    order-status-update: order.status.update.queue
  routing-keys:
    order-creation: order.create
    order-status-update: order.status.update
