spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lmall
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

server:
  port: 8083

rabbitmq:
  exchanges:
    inventory: inventory.exchange
  queues:
    inventory-update: inventory.update.queue
    inventory-prewarm: inventory.prewarm.queue
  routing-keys:
    inventory-update: inventory.update
    inventory-prewarm: inventory.prewarm
